import {versionOf} from './versions';

const STATUSES=['passed','failed','blocked','cancelled','needs_review','running','queued','not_passed'];
const MODES=['prompt','image','image_prompt'],LEVELS=['simple','medium','complex'];
const ended=(j:any)=>!['queued','running'].includes(j.status);
const choice=(p:URLSearchParams,key:string,values:string[])=>{const v=p.get(key)||'';if(v&&!values.includes(v))throw Error('无效筛选项：'+key);return v;};
function integer(p:URLSearchParams,key:string,fallback:number,max:number){const s=p.get(key);if(s===null||s==='')return fallback;if(!/^\d+$/.test(s))throw Error('分页参数无效：'+key);const n=Number(s);if(!Number.isSafeInteger(n)||n<1||n>max)throw Error('分页参数超出范围：'+key);return n;}
function time(p:URLSearchParams,key:string){const v=p.get(key);if(!v)return null;const n=Date.parse(v);if(!/T.*(?:Z|[+-]\d\d:\d\d)$/.test(v)||!Number.isFinite(n))throw Error('时间必须包含时区：'+key);return n;}
export function jobRow(j:any,labels:Record<string,string>,batches:Map<string,any>){
 const versionId=versionOf(j),durationMs=Object.values(j.stages??{}).reduce((n:number,s:any)=>n+(Number.isFinite(s.durationMs)?s.durationMs:0),0);
 return {id:j.id,name:j.plan?.name||j.sceneIR?.name||'未命名场景',prompt:j.prompt??'',validationKind:j.validationKind??'generation',continuation:j.continuation??null,generationMethod:j.generationMethod??'automatic',images:j.images??(j.image?[j.image]:[]),image:j.image?{id:j.image.id,file:j.image.file,name:j.image.name}:null,mode:j.mode,complexity:j.complexity??null,createdAt:j.createdAt,durationMs,status:j.status,stage:j.stage,score:Number.isFinite(j.quality?.score)?j.quality.score:null,version:{id:versionId,label:labels[versionId]??j.pipelineVersion?.label??'历史 · '+j.profile.id.slice(0,8)},assessmentVersion:j.assessmentVersion??null,batch:j.batchId?{id:j.batchId,name:batches.get(j.batchId)?.name??j.batchId,caseId:j.caseId??null}:null,attempt:j.attempt??1,model:j.modelSettings?.model??j.profile.model,reasoningEffort:j.modelSettings?.reasoningEffort??j.profile.reasoningEffort??null,thumbnail:j.runtime?.images?.[0]?'/files/runs/'+j.id+'/runtime/'+encodeURIComponent(j.runtime.images[0]):null,recording:j.runtime?.video?'/files/runs/'+j.id+'/runtime/'+encodeURIComponent(j.runtime.video):null,downloadable:j.stages?.build?.status==='passed'&&ended(j),error:j.error??null};
}
export function queryJobHistory(jobs:any[],params:URLSearchParams,versionList:any[]=[],batchList:any[]=[]){
 const q=(params.get('q')??'').trim();if(q.length>8000)throw Error('Prompt 搜索最多 8000 字符');
 const status=choice(params,'status',STATUSES),mode=choice(params,'mode',MODES),complexity=choice(params,'complexity',LEVELS),sort=choice(params,'sort',['newest','oldest'])||'newest',version=params.get('version')||'',batch=params.get('batch')||'',model=params.get('model')||'',from=time(params,'from'),to=time(params,'to'),requestedPage=integer(params,'page',1,1000000),pageSize=integer(params,'pageSize',20,100);
 if(from!==null&&to!==null&&from>to)throw Error('开始时间不能晚于结束时间');
 const labels=Object.fromEntries(versionList.map(v=>[v.id,v.label])),batchMap=new Map(batchList.map(b=>[b.id,b]));
 const matched=jobs.filter(j=>{const timestamp=Date.parse(j.createdAt);return (!q||(j.prompt??'').toLocaleLowerCase().includes(q.toLocaleLowerCase()))&&(!status||(status==='not_passed'?ended(j)&&j.status!=='passed':j.status===status))&&(!version||versionOf(j)===version)&&(!batch||(batch==='none'?!j.batchId:j.batchId===batch))&&(!mode||j.mode===mode)&&(!complexity||j.complexity===complexity)&&(!model||(j.modelSettings?.model??j.profile.model)===model)&&(from===null||timestamp>=from)&&(to===null||timestamp<=to);}).sort((a,b)=>{const c=a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id);return sort==='oldest'?c:-c;});
 const total=matched.length,pages=Math.max(1,Math.ceil(total/pageSize)),page=Math.min(requestedPage,pages),offset=(page-1)*pageSize;
 const versions=new Map(versionList.map(v=>[v.id,{id:v.id,label:v.label,count:0}])),batches=new Map(batchList.map(b=>[b.id,{id:b.id,name:b.name,count:0}])),models=new Set<string>();
 for(const j of jobs){const id=versionOf(j),v=versions.get(id)??{id,label:j.pipelineVersion?.label??'历史 · '+j.profile.id.slice(0,8),count:0};v.count++;versions.set(id,v);if(j.batchId){const b=batches.get(j.batchId)??{id:j.batchId,name:j.batchId,count:0};b.count++;batches.set(j.batchId,b);}models.add(j.modelSettings?.model??j.profile.model);}
 return {items:matched.slice(offset,offset+pageSize).map(j=>jobRow(j,labels,batchMap)),total,allTotal:jobs.length,page,pageSize,pages,from:total?offset+1:0,to:Math.min(total,offset+pageSize),summary:{passed:matched.filter(j=>j.status==='passed').length,notPassed:matched.filter(j=>ended(j)&&j.status!=='passed').length,active:matched.filter(j=>!ended(j)).length},facets:{versions:[...versions.values()],batches:[...batches.values()],models:[...models].sort()},filters:{q,status,mode,complexity,sort,version,batch,model,from:from===null?null:new Date(from).toISOString(),to:to===null?null:new Date(to).toISOString()}};
}
