import {recordingSink} from './recording-sink.mjs';
import {createBrowserCapture} from '../../engine/packages/engine/dist/facades/devkit.mjs';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {join} from 'node:path';
const [root,url,output]=process.argv.slice(2),browser=createBrowserCapture(root);let session,sink;
try{
 session=await browser.open({backend:'auto',serverUrl:url,headless:true,width:1600,height:900,requireUi:true,outputDir:output});const page=session.page,errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.locator('#scene-hud').waitFor({state:'visible'});await session.capture(undefined,{output:join(output,'with-ui.png'),requireUi:true,timeoutMs:30000});await page.locator('canvas').click();await page.keyboard.press('h');const hidden=await page.locator('#scene-hud').isHidden();const images=[],samples=[];
 const capture=async(name,waitMs=400)=>{await session.capture(undefined,{output:join(output,name),requireUi:false,waitMs,timeoutMs:30000});images.push(name);samples.push({...await page.evaluate(()=>JSON.parse(document.documentElement.dataset.sceneAudit??'null')),at:Date.now()});console.log('Captured '+name);};
 await page.keyboard.press('1');await capture('reference-view-1.png');await page.keyboard.press('2');await capture('reference-view-2.png');await page.keyboard.press('1');await page.keyboard.press('r');await page.keyboard.press('Space');for(let i=0;i<4;i++)await capture('continuous-'+(i+1)+'.png',3500);await page.keyboard.press('Space');await page.keyboard.press('r');await page.keyboard.press('h');const restored=await page.locator('#scene-hud').isVisible();
 const link=page.getByRole('link',{name:'保存录屏'});await link.waitFor({state:'visible'});const recording=await link.getAttribute('href');sink=await recordingSink(join(output,'scene-tour.webm'),new URL(url).origin);const transfer=await page.evaluate(async ({recording,destination})=>{const blob=await(await fetch(recording)).blob();const r=await fetch(destination,{method:'POST',headers:{'Content-Type':'video/webm'},body:blob});if(!r.ok)throw Error('录屏保存失败');return await r.json();},{recording,destination:sink.url});const receipt=await sink.receipt;if(transfer.sha256!==receipt.sha256)throw Error('录屏摘要不一致');
 const first=samples[2],last=samples.at(-1),fps=(last.frames-first.frames)/((last.at-first.at)/1000),movement=Math.hypot(...last.position.map((n,i)=>n-first.position[i]));const report=session.report();errors.push(...report.pageErrors,...report.consoleErrors);const hashes=await Promise.all(images.map(async f=>createHash('sha256').update(await readFile(join(output,f))).digest('hex')));
 const audit=JSON.parse(await readFile(join(root,'assets/scene-audit.json'),'utf8'));const hard={multipleViews:samples[0].selectedView===0&&samples[1].selectedView===1&&hashes[0]!==hashes[1],cameraMotion:movement>.05,nonFlat:audit.geometry?.nonFlat===true&&movement>.05,runtime:fps>0,noErrors:errors.length===0,hudToggle:hidden&&restored,twoReferenceViews:samples[0].selectedView===0&&samples[1].selectedView===1&&hashes[0]!==hashes[1],cameraTranslation:movement>.05,entitiesLoaded:samples.every(s=>s.parts?.length>0&&s.parts.every(p=>p.loaded)&&!s.ambiguousSource),frameRate:fps>=24,video:receipt.bytes>0};const result={hard,images,hashes,video:'scene-tour.webm',recording:receipt,submittedFps:fps,translation:movement,poses:samples.map(({frameTimes,...s})=>s),durationMs:last.at-first.at,errors,engineReport:report,distManifestDigest:createHash('sha256').update(await readFile(join(root,'dist/forgeax-dist.json'))).digest('hex'),source:audit.provenance,scope:'两张静态参考机位、同一机位的连续平移片段；不等于全空间复刻通过'};await writeFile(join(output,'runtime.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({hard,fps,movement}));
}finally{await sink?.close();if(session)await session.page.close({runBeforeUnload:false});await session?.close();}
