import {mkdirSync,readFileSync,copyFileSync,existsSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {ROOT,UPLOADS,read,save,saveJob,event,digest} from './store';
import {CASE,prepareNative,sha} from './native/prepare';
import {SPEC,VISUAL_RULE_IDS,specGate} from './spec';
import {reconstructionPlan} from './native/reconstruction-plan';
import {qualityGate} from './quality';
import {callValidated} from './contracts';
export const NATIVE_CASE='diner-20260922';
export const NATIVE_PROMPT='用复杂场景生成两张图片对应的同一个废弃餐厅，做到完整复刻。保留砖墙与砖拱、木梁屋顶、多格门窗、红褐卡座、格纹桌布、木椅圆桌、街机和彩玻璃吊灯，匹配材质磨损、构图和温暖昏暗日光。可见部分逐项对照，不把推断区域称为精确复刻。必须运行于当前 ForgeaX Engine。';
export function nativeInput(){const images=[1,2].map(i=>{const p=join(CASE,'references/view-'+i+'.png'),id=sha(p),meta={id,file:id+'.png',mime:'image/png',name:'餐厅参考视角'+i+'.png',size:readFileSync(p).length};if(!existsSync(join(UPLOADS,meta.file)))copyFileSync(p,join(UPLOADS,meta.file));save(join(UPLOADS,id+'.json'),meta);return id;});return {prompt:NATIVE_PROMPT,imageIds:images,complexity:'complex',nativeCase:NATIVE_CASE};}
export function nativePlan(){return {name:'旧日餐厅 · 双视角复刻',summary:'同一间废弃餐厅的两个参考视角。原生三维空间、独立精细网格与写实贴图；由当前任务辅助制作，尚非任意图片的全自动复刻。',capabilities:['mapping','consistency'],assumptions:['房间精确尺寸与相机内参为推断。','完全遮挡的后厨和窗外环境为推断。','辅助制作样例不计入全自动管线认证成功率。'],requirements:[['architecture','砖拱、砖墙和木梁构成同一个室内空间'],['openings','多格窗、员工门、玻璃入口和服务窗口与两张参考图对应'],['furniture','褪色红褐卡座、格纹桌布、圆桌及木椅的轮廓和位置一致'],['arcade','窗边街机具有异形侧板、倾斜屏幕、操作台和侧面图案'],['pendants','彩玻璃吊灯、吊链与破损灯罩可辨'],['materials','旧砖、抹灰、木纹、皮革、织物、瓷砖与地毯具有写实材质和磨损'],['lighting','暖色窗光、昏暗室内和两张参考构图得到还原']].map(([id,text])=>({id,text,critical:true,weight:5,source:'image',evidence:['两张原始参考图中的可见区域；完全遮挡区域不作为精确要求'],count:null}))};}
export const NATIVE_JUDGE=`你独立评估两张参考图的餐厅复刻。前两张是用户参考，后续图片是当前 ForgeaX Engine 实际截图。必须以可见画面对照，不采信作者的成功自述。
本例用户要求写实完整复刻，不能以低模风格豁免材质、细节、布局或光照差距。逐项比较砖拱、屋顶木梁、门窗、卡座、桌布、木椅、街机、彩玻璃灯罩、旧化和摄影构图。近似轮廓、类型齐全不等于完整复刻。任何关键项部分还原均标为 partial，明显缺少标 missing。材质图案或比例不匹配必须扣分。
返回 JSON {confidence,summary,specRules:[{id,status,reason,frames}],entityCounts:[],requirements:[{id,verdict,reason,frames}],dimensions:[{id,score,reason,frames}]}。status 为 passed/failed/needs_review，verdict 为 met/partial/missing。五维 id 为 coverage/spatial/shape/material/readability，score 为 0..5，confidence 为 0..1。每条需求与每个输入规范 ID 各出现一次。frames 只能引用给定实际截图文件名，不能引用参考图片当成运行证据。entityCounts 返回空数组，因为本例评估空间还原而非固定预制件计数。
图片没有展示的区域不可判为已经验证。两幅静态参考相机截图与随后同一相机的连续观测分开，不能把静态比较切换当作录屏切镜。不得凭静态截图断言没有闪烁或全程流畅。所有摘要与理由使用中文。`;
export function nativeAssessment(plan:any,review:any,runtime:any,policy:any){const frames=new Set(runtime.images);for(const x of [...review.requirements,...review.dimensions,...review.specRules])if(!Array.isArray(x.frames)||x.frames.some((f:string)=>!frames.has(f)))throw Error('复刻评估引用了不存在的运行帧');const hard={...runtime.hard,build:runtime.buildEvidence===true,catalog:runtime.catalogEvidence===true,frameRate:runtime.hard.frameRate&&runtime.submittedFps>=policy.minSubmittedFps,framing:review.specRules.find((r:any)=>r.id==='S06')?.status==='passed'},quality=qualityGate(plan,review,hard,policy),spec=specGate(review,runtime,plan,{passed:true,checks:[],semanticCounts:{}});return {quality,spec,status:[quality.status,spec.status].includes('failed')?'failed':'needs_review'};}
export async function runNative({job,dir,signal,stage,command,preview}:any){
 let layout:any;const plan=nativePlan(),project=join(dir,'project'),PROTO=resolve(ROOT,'../prototype');job.specSource={version:SPEC.version,sha256:SPEC.sha256,sourceUrl:SPEC.sourceUrl};job.plan=await stage('plan',async()=>{layout=await reconstructionPlan(job,dir,signal);plan.summary=layout.interpretation;plan.assumptions=layout.assumptions;save(join(dir,'plan.json'),plan);save(join(dir,'spec-snapshot.json'),SPEC);return plan;});
 await stage('generate',async()=>{prepareNative(project,job.id,layout);job.generationMethod='assisted-native-scene';job.generationModel='Astra 双图观察与视觉评估；辅助建筑初值及原生资产构造';job.nativeProvenance={referenceSource:{url:'https://edgar_a_martinez.artstation.com/projects/wJVo9w',author:'Edgar A. Martinez',inputToGallery:[3,1],additionalContext:'第 5 张后厨视角，仅辅助理解，未作为用户输入或评分替代'},atlasSha256:sha(join(CASE,'material-atlas.png')),detailAtlasSha256:sha(join(CASE,'detail-material-atlas-v1.png')),arcadeAtlasSha256:sha(join(CASE,'arcade-material-atlas-v1.png')),observationKey:job.reconstruction.observationKey,layoutSha256:sha(join(dir,'reference-layout.json')),references:job.images.map((i:any)=>i.id),sourceSha256:digest(['mesh.ts','micro-surface.ts','reconstruction.scene.ts','asset-library.ts','cloth.ts','arcade-materials.ts','tabletop.ts','table-litter.ts','fitting.ts','diner-layout-seed.json','material-binding.ts'].map(f=>readFileSync(join(ROOT,'src/native',f),'utf8')).join('\n')),inferredRegions:plan.assumptions};save(join(dir,'native-provenance.json'),job.nativeProvenance);const materials=join(dir,'materials');mkdirSync(materials,{recursive:true});for(const f of ['material-atlas.png','material-prompt.zh.txt','detail-material-atlas-v1.png','detail-material-prompt.zh.txt','arcade-material-atlas-v1.png','arcade-material-prompt.zh.txt','arcade-material-provenance.json'])copyFileSync(join(CASE,f),join(materials,f));save(join(dir,'generation-brief.json'),{original:job.prompt,method:job.generationMethod,assumptions:plan.assumptions,acceptance:job.policy});});
 for(const [name,op] of [['export','generate'],['build','build'],['verify','verify']])await stage(name,async()=>{if(name==='build')await command(['bun',join(ROOT,'src/native/bindings.ts'),project]);await command(['bun',join(PROTO,'bin/pipeline.ts'),op]);});
 const report=read(join(project,'evidence/run-report.json'));job.objectCount=report.generated.meshes;job.entityCount=report.generated.meshes;job.nativeMetrics=report.generated;
 const runtime=await stage('runtime',async()=>{saveJob(job);job.previewUrl=await preview(job.id);saveJob(job);const output=join(dir,'runtime');mkdirSync(output,{recursive:true});await command(['node',join(ROOT,'src/native-capture.mjs'),join(project,'game'),job.previewUrl,output],150000);const result=read(join(output,'runtime.json'));if(result.distManifestDigest!==report.distManifestDigest)throw Error('运行证据与构建摘要不一致');result.buildEvidence=job.stages.build.status==='passed';result.catalogEvidence=job.stages.verify.status==='passed';save(join(output,'runtime.json'),result);job.runtime=result;return result;});
 const review=await stage('judge',async()=>{const images=[...job.images.map((i:any)=>({path:join(UPLOADS,i.file),mime:i.mime})),...runtime.images.map((f:string)=>({path:join(dir,'runtime',f),mime:'image/png'}))];const res=await callValidated({modelSettings:job.modelSettings,role:'judge',signal,maxTokens:6500,images,system:NATIVE_JUDGE,text:JSON.stringify({originalPrompt:job.prompt,plan,frameNames:runtime.images,referenceImages:2,visualSpecRules:SPEC.rules.filter(r=>VISUAL_RULE_IDS.includes(r.id)),countKinds:[],measurements:{hard:runtime.hard,fps:runtime.submittedFps}})},dir,(v:any)=>{nativeAssessment(plan,v,runtime,job.policy);return v;});save(join(dir,'review.json'),res.value);job.review=res.value;return res.value;});
 const result=await stage('gate',async()=>nativeAssessment(plan,review,runtime,job.policy));Object.assign(job,result);save(join(dir,'quality.json'),result.quality);save(join(dir,'spec.json'),result.spec);event(job,'complete',job.status==='failed'?'已生成可预览场景，但未达到完整复刻要求':'已生成，等待逐项复核；辅助制作不计全自动成功率');
}
