import {bindObservedSpace,validateObservations} from './geometry/reference-observations';
import {test,expect,afterAll} from 'bun:test';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {ReferenceBaselines} from './reference-baseline';
import {ImprovementLedger} from './improvement-governance';
import {spatialGate,validateSpaceRelations} from './geometry/blockout';
import {comparable} from './score-history';
import {createJob} from './runner';
import {digest,save} from './store';
const root=mkdtempSync(join(tmpdir(),'scene-vnext-'));afterAll(()=>rmSync(root,{recursive:true,force:true}));
function fixture(){const p=join(root,crypto.randomUUID()),up=join(p,'uploads');mkdirSync(up,{recursive:true});const pixels=Buffer.from('real-test-content'),id=digest(pixels);writeFileSync(join(up,id+'.png'),pixels);save(join(up,id+'.json'),{id,file:id+'.png',mime:'image/png'});return {r:new ReferenceBaselines(join(p,'refs'),up),id,up};}
test('所有创建路径在模型调用前要求图片确认，旧无图或未经确认不能绕过',()=>{for(const options of [{},{reuseSceneFrom:crypto.randomUUID()},{reuseCheckpoint:'old'},{recoverySourceJobId:crypto.randomUUID()},{batchId:'batch'}])expect(()=>createJob({prompt:'测试',imageIds:[]},options)).toThrow('REFERENCE_APPROVAL_REQUIRED');});
test('确认与启动幂等，篡改描述、图片顺序或像素必须重新确认',()=>{const {r,id,up}=fixture(),v=r.create({prompt:'庭院',imageIds:[id]}),input={prompt:'庭院',imageIds:[id],baselineId:v.id};expect(()=>r.assert(input)).toThrow();r.approve(v.id);let starts=0;expect(r.start(input,()=>{starts++;return {id:'job-one'}}).id).toBe('job-one');expect(r.start(input,()=>{starts++;return {id:'job-two'}}).id).toBe('job-one');expect(starts).toBe(1);expect(()=>r.assert({...input,prompt:'庭院改了'})).toThrow();expect(()=>r.reject(v.id,'')).toThrow();writeFileSync(join(up,id+'.png'),'changed');expect(()=>r.assert(input)).toThrow('摘要');});
test('驳回撤销确认，补充修订不继承许可，刷新后可恢复待确认状态',()=>{const {r,id}=fixture(),v=r.create({prompt:'庭院',imageIds:[id]});r.approve(v.id);r.reject(v.id,'房间过窄');const next=r.create({prompt:'更宽的庭院',imageIds:[id]},v.id);expect(next.approval).toBeNull();expect(next.parentId).toBe(v.id);expect(new ReferenceBaselines(r.root,r.uploads).get(next.id).status).toBe('awaiting_confirmation');});
test('生成数量严格最多五张，生图失败不会开始场景，调用中不允许再次生成',async()=>{const {r}=fixture(),v=r.create({prompt:'海边灯塔'});let calls=0;await expect(r.generate(v.id,6,async()=>{calls++;return []})).rejects.toThrow();expect(calls).toBe(0);const failed=await r.generate(v.id,2,async()=>{calls++;throw Error('供应商受阻')});expect(failed.status).toBe('failed');expect(failed.approval).toBeNull();expect(failed.jobId).toBeNull();await expect(r.generate(v.id,2,async()=>[])).rejects.toThrow();expect(calls).toBe(1);});
test('跨版本、模型和新任务共享修正额度；恢复不重置；停止时输出诊断',()=>{const l=new ImprovementLedger(join(root,'ledger')),input={prompt:'餐厅',images:[{id:'x'}]},id=l.enter(input,'a');l.reserveRepair(id,'graybox','通道被墙挡住，修正开口几何');l.enter({...input,model:'new'},'b',[],{improvementId:id});expect(l.get(id).repairs).toBe(1);l.reserveRepair(id,'final','调整透视');expect(()=>l.enter({...input,pipelineVersion:'new'},'c')).toThrow('IMPROVEMENT_STOPPED');expect(l.get(id).diagnosis).toBeDefined();});
test('同规则连续无提升会停止，不用高总分掩盖关键关系缺失',()=>{const l=new ImprovementLedger(join(root,'no-gain')),id=l.enter({prompt:'测试',images:[]},'a');for(const score of [60,60.5,61])l.result(id,{kind:'final',comparison:'same',score});expect(l.get(id).stopped).toBeTruthy();const space={spatialRelations:[{id:'passage',critical:true}]},review={score:4.5,confidence:.9,relations:[{id:'passage',score:2,verdict:'missing',reason:'门洞封堵',frames:['reference-1.png']}]};expect(spatialGate(review,space,['reference-1.png']).passed).toBe(false);expect(()=>spatialGate({...review,relations:[]},space,['reference-1.png'])).toThrow();expect(()=>spatialGate({...review,relations:[{...review.relations[0],frames:['fake.png']}]},space,['reference-1.png'])).toThrow();});
test('不同规则、模型或参考基准不计算质量涨幅',()=>{const a={referenceKey:'same',prompt:'院子',scoring:'v4',protocol:'p',model:{model:'astra',reasoningEffort:'xhigh'},policy:{score:80}};expect(comparable(a,{...a})).toBe(true);for(const b of [{...a,scoring:'v5'},{...a,referenceKey:'other'},{...a,model:{model:'another'}}])expect(comparable(a,b)).toBe(false);});

test('空间规划不能凭空增加实例、丢失地标或降低观察关系关键性',()=>{const o={landmarks:[{id:'door'}],relations:[{id:'entry',description:'入口保持开放纵深',critical:true,landmarkIds:['door']}]},space={program:{instances:[{id:'entrance'}]},observedBindings:[{landmarkId:'door',instanceIds:['entrance']}],spatialRelations:[{id:'entry',description:'入口保持开放纵深',critical:true,instanceIds:['entrance']}]};expect(bindObservedSpace(space,o)).toEqual(space);expect(()=>bindObservedSpace({...space,program:{instances:[{id:'entrance'},{id:'invented'}]}},o)).toThrow('凭空');expect(()=>bindObservedSpace({...space,spatialRelations:[{...space.spatialRelations[0],critical:false}]},o)).toThrow('关键性');});
