import {test,expect} from 'bun:test';
import {qualityDecision,buildQualityDiagnosis,qualityFailure} from './quality-diagnosis';
import {readableBlockout} from './geometry/blockout-presentation';
const ledger=()=>({id:'experiment',limits:{repairs:2,calls:100,noGain:2,minGain:2},repairs:0,calls:3,noGain:0});
test('未通过自动修复到共享上限，达到门槛立即结束',()=>{const l=ledger();expect(qualityDecision(l).action).toBe('repair');l.repairs=1;expect(qualityDecision(l).action).toBe('repair');l.repairs=2;expect(qualityDecision(l)).toMatchObject({action:'diagnose',code:'repair-limit'});expect(qualityDecision(l,true).action).toBe('pass');});
test('调用和连续无进展上限分别给出原因，不因恢复任务重置',()=>{expect(qualityDecision({...ledger(),calls:100}).code).toBe('call-limit');expect(qualityDecision({...ledger(),noGain:2}).code).toBe('no-gain');expect(qualityDecision({...ledger(),stopped:'门槛冲突待诊断'})).toMatchObject({action:'diagnose',reason:'门槛冲突待诊断'});});
test('诊断覆盖跨任务历史、具体差距、证据不足和优化验证，不虚称模型根因',()=>{const make=(id:string,score:number,at:number)=>({id,status:'failed',stage:'graybox',pipelineVersion:{label:'rc.'+id},blockout:{rounds:[{round:0,path:'generation/blockout/0',endedAt:at,passed:false,threshold:{space:4,confidence:.7},frames:['reference-1.png'],review:{score,confidence:.6,relations:[{id:'door',score:2,verdict:'partial',reason:'门头出画，边界不够清楚',frames:['reference-1.png']}]}}]}});const a=make('a',3,1),b=make('b',3.2,2),r=buildQualityDiagnosis(b,{...ledger(),repairs:2},[a,b],{b:{spatialRelations:[{id:'door',critical:true,description:'门窗关系'}]}});expect(r.rounds.map(x=>x.score)).toEqual([3,3.2]);expect(r.gaps[0]).toMatchObject({description:'门窗关系',occurrences:2,critical:true});expect(r.findings.find(x=>x.category==='验收证据')?.certainty).toBe('已确认');expect(r.findings.find(x=>x.category==='模型能力')?.certainty).toBe('未证实为根因');expect(r.plan).toHaveLength(3);expect(qualityFailure({...b,status:'running'})).toBe(false);expect(qualityFailure(b)).toBe(true);});
test('灰模诊断只改变显示，不修改任何几何、实例或相机，不使用参考纹理',()=>{const s={cameras:[{position:[1,2,3],target:[0,0,0],fov:1}],textures:[{id:'old'}],program:{materials:[],instances:[{id:'a',position:[1,0,0]}],templates:[{id:'wall',parts:[{id:'p',material:'old',shape:{type:'box'},position:[0,1,2]}]},{id:'door',parts:[{id:'d',material:'old',shape:{type:'box'}}]}]}};const before=JSON.stringify(s),r=readableBlockout(s);expect(JSON.stringify(s)).toBe(before);expect(r.cameras).toEqual(s.cameras);expect(r.program.instances).toEqual(s.program.instances);const clean=(t:any[])=>t.map(x=>({...x,parts:x.parts.map(({material,...p}:any)=>p)}));expect(clean(r.program.templates)).toEqual(clean(s.program.templates));expect(r.textures).toEqual([]);expect(new Set(r.program.materials.map((m:any)=>m.color[0])).size).toBeGreaterThan(1);});

import {spatialGate} from './geometry/blockout';
import {ImprovementLedger} from './improvement-governance';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
test('快速灰模允许局部偏差但保留大结构阻断；旧规则结果不变',()=>{const space={spatialRelations:[{id:'door',critical:true}]},v={score:3.2,confidence:.7,relations:[{id:'door',score:3,verdict:'partial',reason:'门和主通路成立，门框占幅有偏差',frames:['reference-1.png']}]},frames=['reference-1.png'],policy={spatialPreflight:'coarse-v2'};expect(spatialGate(v,space,frames).passed).toBe(false);expect(spatialGate(v,space,frames,policy).passed).toBe(true);for(const r of [{...v.relations[0],score:1},{...v.relations[0],verdict:'missing'}])expect(spatialGate({...v,relations:[r]},space,frames,policy).passed).toBe(false);expect(spatialGate({...v,confidence:.3},space,frames,policy).passed).toBe(false);});
test('新策略追加一次修复有审计、幂等，原次数与调用不重置',()=>{const root=mkdtempSync(join(tmpdir(),'strategy-test-'));try{const l=new ImprovementLedger(root),id=l.enter({prompt:'旧石阶',images:[]},'first');l.reserveRepair(id,'graybox','左侧关系错误');l.reserveRepair(id,'graybox','相机裁切');l.call(id,'scene-space');l.markStopped(id,'已达上限',{report:'old.json'});const change={id:'spatial-preflight-v2',reason:'灰模改为大致验证，最终标准保留',pipelineVersion:{label:'candidate'},additionalRepairs:1};let v=l.reviseStrategy(id,change);expect(v.repairs).toBe(2);expect(v.calls).toBe(1);expect(v.limits.repairs).toBe(3);expect(v.stopped).toBeUndefined();expect(v.strategyRevisions[0].before.stopped).toBe('已达上限');v=l.reviseStrategy(id,change);expect(v.limits.repairs).toBe(3);expect(v.strategyRevisions).toHaveLength(1);}finally{rmSync(root,{recursive:true,force:true});}});
