import {project} from './runtime-metrics.mjs';
export const RECIPE_INSTRUCTIONS=`Return JSON only, no code. Scene is a recognizable low-poly 3D environment for continuous moving-camera recording, not a 2D billboard. Work in Z-up, ground at Z=0. Center scene around XY=0. Keep all objects within X/Y ±16 and Z -4..24 (bases/water may extend below ground). Use composition, silhouette, multiple depths, visible major structures and distinguishable materials. Primitive objects may overlap intentionally to assemble structures. No UI text pretending geometry. No external assets. Maximum 40 objects and 12 materials. Keep JSON compact. Round coordinates to 2 decimal places. Prioritize major structures without dropping frozen requirements. JSON schema: {name:string,materials:[{id:string,color:[r,g,b,1],roughness:number,metallic:number}],objects:[{id:string,label:string,requirementIds:string[],shape:'box'|'frustum'|'sphere',position:[x,y,z],size:[width,depth,height],rotation:number,material:string,radiusBottom?:number,radiusTop?:number,sides?:number}]}. Colors are linear 0..1. For box/sphere position is ground-bottom center; rotation is yaw radians. Frustum stands vertically with bottom and top radii and size[2] height. Sphere uses size[0]/2 radius. A tree, lamp, curved roof etc can be composed from several primitives. Realize every frozen requirement, and ensure details are large enough to read in wide views.`;
export function validatePlan(p:any){
 if(typeof p?.name!=='string'||typeof p?.summary!=='string'||!Array.isArray(p.requirements)||!p.requirements.length||p.requirements.length>15)throw Error('需求计划格式不完整');
 const ids=new Set();for(const r of p.requirements){if(!/^[a-zA-Z0-9_-]+$/.test(r.id)||ids.has(r.id)||typeof r.text!=='string'||typeof r.critical!=='boolean'||!Number.isFinite(r.weight)||r.weight<=0||r.weight>5)throw Error('需求条目无效');ids.add(r.id);}return p;
}
export function validateRecipe(r:any,plan:any){
 if(!Array.isArray(r?.objects)||r.objects.length<1||r.objects.length>(r.semanticEntities?512:120)||!Array.isArray(r.materials)||!r.materials.length||r.materials.length>(r.semanticEntities?128:16))throw Error('场景对象或材质数量超出契约');
 const mats=new Set();for(const m of r.materials){if(!/^[a-zA-Z0-9_-]+$/.test(m.id)||mats.has(m.id)||!Array.isArray(m.color)||m.color.length!==4||m.color.some((n:any)=>!Number.isFinite(n)||n<0||n>1))throw Error('材质无效');mats.add(m.id);for(const k of ['roughness','metallic'])if(!Number.isFinite(m[k])||m[k]<0||m[k]>1)throw Error('材质参数无效');}
 const ids=new Set();for(const o of r.objects){if(!/^[a-zA-Z0-9_-]+$/.test(o.id)||ids.has(o.id)||!['box','frustum','sphere','leaf'].includes(o.shape)||!mats.has(o.material))throw Error('对象身份或形状无效');ids.add(o.id);for(const k of ['position','size'])if(!Array.isArray(o[k])||o[k].length!==3||o[k].some((v:any)=>!Number.isFinite(v)||Math.abs(v)>32))throw Error('对象坐标无效');if(o.size.some((n:number)=>n<=0)||!Number.isFinite(o.rotation))throw Error('对象尺寸无效');if(!Array.isArray(o.requirementIds)||o.requirementIds.some((id:any)=>typeof id!=='string'))throw Error('对象需求归属无效');if(o.shape==='frustum'&&(!Number.isFinite(o.radiusBottom)||!Number.isFinite(o.radiusTop)||o.radiusBottom<=0||o.radiusTop<0||o.radiusBottom>16||o.radiusTop>16))throw Error('锥体半径无效');o.sides=Math.max(4,Math.min(16,Math.round(o.sides??8)));}
 r.annotationWarnings=r.objects.flatMap((o:any)=>o.requirementIds.filter((id:string)=>!plan.requirements.some((p:any)=>p.id===id)).map((id:string)=>({object:o.id,unknownRequirement:id})));return r;
}
export function bounds(recipe:any){
 const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];
 for(const o of recipe.objects.filter((o:any)=>o.role!=='ground')){const radial=Math.max(Math.hypot(o.size[0],o.size[1]),2*(o.radiusBottom??0),2*(o.radiusTop??0))/2;for(let k=0;k<3;k++){min[k]=Math.min(min[k],o.position[k]-(k===2?0:radial));max[k]=Math.max(max[k],o.position[k]+(k===2?o.size[2]:radial));}}
 const center=[(min[0]+max[0])/2,(min[2]+max[2])/2,-(min[1]+max[1])/2];const extent=Math.max(max[0]-min[0],max[1]-min[1],max[2]-min[2]);const height=Math.max(3,extent*.34),envelope=[];for(const x of [min[0],max[0]])for(const y of [min[2],max[2]])for(const z of [-max[1],-min[1]])envelope.push([x,y,z]);let radius=Math.max(6,extent*.86);
 for(let attempt=0;attempt<80;attempt++){let fits=true;for(let k=0;k<32;k++){const angle=k*Math.PI/16,pose={position:[center[0]+Math.cos(angle)*radius,center[1]+height,center[2]+Math.sin(angle)*radius],target:center};if(envelope.some(p=>{const q=project(p,pose);return q.depth<=0||q.x<38||q.x>922||q.y<26||q.y>614;})){fits=false;break;}}if(fits)return {center,radius,height,extent,envelope,framing:'all non-ground envelope corners across 32 orbit positions; 4 percent margin'};radius*=1.04;}throw Error('无法同时容纳主体与关键环境的环绕构图');
}
