const dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),sub=(a,b)=>a.map((v,i)=>v-b[i]),norm=a=>{const n=Math.hypot(...a);return a.map(v=>v/n)},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
export function project(point,pose,width=960,height=640){const forward=norm(sub(pose.target,pose.position)),right=norm(cross(forward,[0,1,0])),up=cross(right,forward),relative=sub(point,pose.position),depth=dot(relative,forward),f=height/(2*Math.tan(Math.PI/6));return {x:width/2+dot(relative,right)*f/depth,y:height/2-dot(relative,up)*f/depth,depth};}
export function analyzeRun(samples,audit){
 if(samples.length<3||samples.some(s=>!s?.position?.every(Number.isFinite)))throw Error('缺少相机真实位姿');
 const clippedCorners=samples.flatMap((s,i)=>(audit.camera.envelope??[]).map(p=>project(p,s)).filter(p=>p.depth<=0||p.x<0||p.x>960||p.y<0||p.y>640).map(p=>({frame:i+1,...p})));
 const positions=samples.map(s=>s.position),maxDisplacement=Math.max(...positions.map(p=>Math.hypot(...sub(p,positions[0]))));
 const depthRanges=samples.map(s=>{const ds=audit.landmarks.map(l=>project(l.position,s).depth);return Math.max(...ds)-Math.min(...ds)});
 const frames=samples.map((s,i)=>{const points=audit.landmarks.filter(l=>l.role==='subject').map(l=>{const p=project(l.position,s),r=Math.max(...l.size)/2;return {...p,r:r*640/(2*Math.tan(Math.PI/6)*p.depth)}});const minX=Math.min(...points.map(p=>p.x-p.r)),maxX=Math.max(...points.map(p=>p.x+p.r)),minY=Math.min(...points.map(p=>p.y-p.r)),maxY=Math.max(...points.map(p=>p.y+p.r));return {frame:'view-'+(i+1)+'.png',widthRatio:(maxX-minX)/960,heightRatio:(maxY-minY)/640,estimate:'projected primitive bounding spheres; not visible pixel mask'};});
 const minHeightRatio=Math.min(...frames.map(f=>f.heightRatio));
 const expected=audit.parts?.map(p=>p.id)??samples[0].parts?.map(p=>p.id)??[];const missingParts=[...new Set(samples.flatMap(s=>expected.filter(id=>s.parts?.filter(p=>p.id===id&&p.loaded===true).length!==1)))];if(!expected.length)missingParts.push('NO_EXPECTED_PARTS');
 const t=samples.at(-1).frameTimes??[],sorted=t.filter(n=>Number.isFinite(n)&&n>0).sort((a,b)=>a-b),p95=sorted[Math.floor(sorted.length*.95)]??Infinity;
 const fpsWindows=[];for(let i=0;i<sorted.length-60;i+=60){const x=t.slice(i,i+60);fpsWindows.push(60000/x.reduce((a,b)=>a+b,0))}
 return {composition:{checked:!!audit.camera.envelope?.length,clippedCorners},cameraEvidence:{positions,maxDisplacement,depthRanges,source:'actual ECS camera Transform + declared geometry landmarks with runtime binding checks',frameCount:samples.at(-1).frames-samples[0].frames},subjectMeasurement:{frames,minHeightRatio,safeFraming:minHeightRatio>=.25,threshold:{minProjectedHeightRatio:.25,origin:'experimental engineering threshold; source document specifies no numeric pass threshold'},requiresVisualReview:true},performance:{samples:sorted.length,p95FrameMs:p95,minWindowFps:fpsWindows.length?Math.min(...fpsWindows):0},missingParts,hard:{framing:!audit.camera.envelope?.length||clippedCorners.length===0,cameraMotion:maxDisplacement>Math.max(.2,audit.camera.radius*.05),nonFlat:Math.min(...depthRanges)>.5&&missingParts.length===0,multipleViews:samples.length>=6,frameRate:p95<100&&fpsWindows.length>0&&Math.min(...fpsWindows)>=10,entitiesLoaded:missingParts.length===0}};
}
