import {test,expect} from 'bun:test';
import {verifiedRuntimeEvidence} from './runtime-evidence';
const stages=['candidate','generate-export','generation-budget','publish-assets','engine-binding','project-check','engine-build','catalog','asset-verify','asset-ready','engine-status'];
function fixture(){const expected={engineSha:'a'.repeat(40),generatorSha:'b'.repeat(40)},digest='c'.repeat(64);return {expected,digest,report:{...expected,stages:Object.fromEntries(stages.map(s=>[s,{status:'passed'}])),buildInputDigest:'d'.repeat(64),distManifestDigest:digest,catalog:{sha256:'e'.repeat(64)}},runtime:{distManifestDigest:digest,hard:{runtime:true,entitiesLoaded:true,noErrors:true,frameRate:true},submittedFps:42,performance:{p95FrameMs:32,minWindowFps:30},recording:{decodedFps:28},images:['reference-1.png']}};}
test('引擎事实来自冻结构建与同一浏览器产物，不声称视觉达标',()=>{const f=fixture(),v=verifiedRuntimeEvidence(f.report,f.runtime,f.expected,f.digest,10);expect(v.engine).toBe('ForgeaX Engine');expect(v.runtime.frames).toEqual(['reference-1.png']);expect(v.scope).toContain('不证明画面还原');expect(v).not.toHaveProperty('quality');});
test('旧产物、错误引擎、缺失检查和资源加载失败不能传给评分器冒充已验证',()=>{
 for(const mutate of [(f:any)=>f.report.engineSha='f'.repeat(40),(f:any)=>delete f.report.stages['asset-ready'],(f:any)=>f.report.stages['engine-build'].status='failed',(f:any)=>f.runtime.distManifestDigest='f'.repeat(64),(f:any)=>f.digest='f'.repeat(64),(f:any)=>delete f.report.catalog.sha256,(f:any)=>f.runtime.hard.entitiesLoaded=false,(f:any)=>f.runtime.images=[]]){const f=fixture();mutate(f);expect(()=>verifiedRuntimeEvidence(f.report,f.runtime,f.expected,f.digest,10)).toThrow('RUNTIME_EVIDENCE_INVALID');}
});

test('已测帧率与实际任务门槛一同传递，更新帧与录屏帧分别报告',()=>{const f=fixture(),v=verifiedRuntimeEvidence(f.report,f.runtime,f.expected,f.digest,20);expect(v.runtime.performance).toMatchObject({submittedFps:42,minimumSubmittedFps:20,frameRateCheckPassed:true,p95FrameMs:32,minWindowFps:30,recordedVideoFps:28});expect(v.runtime.performance.scope).toContain('不证明');expect(v).not.toHaveProperty('score');});
test('缺失或伪通过的帧率以及非法测量不能冒充运行事实',()=>{for(const change of [(f:any)=>f.runtime.submittedFps=9,(f:any)=>f.runtime.submittedFps=NaN,(f:any)=>delete f.runtime.submittedFps,(f:any)=>f.runtime.hard.frameRate=false,(f:any)=>f.runtime.performance.p95FrameMs=-2,(f:any)=>f.runtime.recording.decodedFps=Infinity]){const f=fixture();change(f);expect(()=>verifiedRuntimeEvidence(f.report,f.runtime,f.expected,f.digest,10)).toThrow('RUNTIME_EVIDENCE_INVALID');}const f=fixture();expect(()=>verifiedRuntimeEvidence(f.report,f.runtime,f.expected,f.digest,50)).toThrow('帧率');});
test('历史缺少可选窗口或录屏测量时明确为null，不补造数值',()=>{const f:any=fixture();delete f.runtime.performance;delete f.runtime.recording;const v=verifiedRuntimeEvidence(f.report,f.runtime,f.expected,f.digest,10);expect(v.runtime.performance).toMatchObject({submittedFps:42,p95FrameMs:null,minWindowFps:null,recordedVideoFps:null});});
