import {join} from 'node:path';
import {existsSync,readdirSync,mkdirSync,cpSync,readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {DATA,read,save,digest,runDir,listJobs} from './store';
export function saveAssessment(job:any,dir:string){const id=randomUUID(),folder=join(dir,'score-history',id);mkdirSync(folder,{recursive:true});for(const f of ['quality.json','review.json','spec-report.json','judge-receipt.json','runtime'])if(existsSync(join(dir,f)))cpSync(join(dir,f),join(folder,f),{recursive:true});const r=scoreRow(job,{id,round:job.iteration??0,type:job.assessmentVersion?'reevaluation':job.refineScene?'manual-repair':job.iteration?'automatic-repair':'initial',createdAt:Date.now(),artifactDigest:job.runtime?.distManifestDigest,href:'/files/runs/'+job.id+'/score-history/'+id+'/',immutable:true});save(join(folder,'assessment.json'),r);return r;}
function scoreRow(j:any,extra:any={}){return {id:j.id,jobId:j.id,prompt:j.prompt,pipeline:j.pipelineVersion?.label??'历史',pipelineId:j.pipelineVersion?.id,assessmentPipeline:j.assessmentVersion?.label??j.pipelineVersion?.label,scoring:j.policy?.version,protocol:j.assessmentProfile?.assessmentProtocolSha256??j.profile?.assessmentProtocolSha256,model:j.modelSettings??{model:j.profile?.model,reasoningEffort:j.profile?.reasoningEffort},referenceKey:digest(JSON.stringify((j.images??[]).map(i=>i.id))),policy:j.policy,score:j.quality?.score??null,dimensions:j.review?.dimensions??[],status:j.status,round:j.iteration??0,type:j.validationKind??'generation',createdAt:Date.parse(j.createdAt),artifactDigest:j.runtime?.distManifestDigest,href:'/files/runs/'+j.id+'/',immutable:false,...extra};}
export function comparable(a:any,b:any){return a.referenceKey===b.referenceKey&&a.prompt===b.prompt&&a.scoring===b.scoring&&a.protocol===b.protocol&&JSON.stringify(a.model)===JSON.stringify(b.model)&&JSON.stringify(a.policy)===JSON.stringify(b.policy);}
export function scoreHistory(jobs=listJobs()){const rows:any[]=[];for(const j of jobs){const dir=runDir(j.id),p=join(dir,'score-history');if(existsSync(p)){for(const id of readdirSync(p)){const f=join(p,id,'assessment.json');if(existsSync(f))rows.push(read(f));}}else {const cycles=j.visualIterations?.cycles??[];for(const c of cycles){const f=join(dir,'iterations',String(c.index),'candidate.json');if(existsSync(f)){const s=read(f);rows.push(scoreRow({...j,...s.fields},{id:j.id+':iteration:'+c.index,round:c.index,createdAt:c.endedAt,type:c.index?'automatic-repair':j.validationKind,href:'/files/runs/'+j.id+'/iterations/'+c.index+'/',immutable:true}));}}const assessmentDir=join(dir,'assessments');if(existsSync(assessmentDir))for(const n of readdirSync(assessmentDir)){const f=join(assessmentDir,n,'job.json');if(existsSync(f))rows.push(scoreRow(read(f),{id:j.id+':assessment:'+n,type:'历史复评',href:'/files/runs/'+j.id+'/assessments/'+n+'/',immutable:true}));}if(!cycles.length||!rows.some(r=>r.jobId===j.id))rows.push(scoreRow(j));}
 for(const r of j.blockout?.rounds??[])rows.push(scoreRow(j,{id:j.id+':blockout:'+r.round,scoring:'spatial-blockout-v1',score:r.review.score*20,status:r.passed?'passed':'failed',round:r.round,type:'空间灰模（非综合分）',dimensions:r.review.relations,createdAt:r.endedAt,href:'/files/runs/'+j.id+'/'+r.path+'/',artifactDigest:r.runtimeDigest,immutable:true}));}
 return rows.sort((a,b)=>b.createdAt-a.createdAt);}
