import {test,expect} from 'bun:test';
import {DEFAULT_POLICY,HARD_CHECKS,DIMENSIONS,qualityGate} from './quality';
import {freezeStage,stageGate} from './stage-gate';
function fixture(){
 const batch:any={id:'batch',pipelineVersion:{id:'version'},profile:{id:'profile'},policy:{...DEFAULT_POLICY,maxAttempts:1},cases:Array.from({length:10},(_,i)=>({id:'c'+i,prompt:'未见场景 '+i,imageIds:[],complexity:'complex',mode:'prompt'}))};batch.stageValidation=freezeStage(batch,[]);
 const jobs=batch.cases.map((c:any,i:number)=>{const hard=Object.fromEntries(HARD_CHECKS.map(k=>[k,true])),plan={requirements:[{id:'R1',critical:true,weight:1}]},review={requirements:[{id:'R1',verdict:'met',reason:'固定测试证据',frames:['reference-1.png']}],dimensions:DIMENSIONS.map(d=>({id:d.id,score:4,reason:'固定测试证据',frames:['reference-1.png']})),confidence:.9},quality=qualityGate(plan,review,hard,batch.policy),first={index:0,status:'failed',score:65,startedAt:10,endedAt:20},best={index:1,status:'passed',score:quality.score,startedAt:21,endedAt:40};return {...c,id:'j'+i,batchId:batch.id,caseId:c.id,attempt:1,retryRoot:'j'+i,validationKind:'generation',pipelineVersion:batch.pipelineVersion,profile:batch.profile,policy:batch.policy,status:i<8?'passed':'failed',iterationPolicy:{version:'bounded-visual-v1',maxVisualRepairs:2},visualIterations:{status:'completed',maxRepairs:2,cycles:[first,best],bestIndex:1},selectedIteration:1,firstDraft:first,quality,plan,review,stages:{build:{status:'passed'},verify:{status:'passed'}},runtime:{hard:Object.fromEntries(Object.entries(hard).filter(([k])=>!['build','catalog'].includes(k))),submittedFps:30},spec:{status:'passed'},realizationStatus:'passed'};});return {batch,jobs};
}
test('十例八次单提交内达标仅证明阶段通过，自动修正不记首稿成功',()=>{const {batch,jobs}=fixture(),r=stageGate(batch,jobs)!;expect(r).toMatchObject({status:'passed',sampleCount:10,passed:8,rate:.8,firstPass:0,certifiesStableVersion:false});});
test('待完成仍按十例固定分母，九成已返回成功不能提前认证',()=>{const {batch,jobs}=fixture();expect(stageGate(batch,jobs.slice(0,8))).toMatchObject({status:'in_progress',passed:8,rate:.8,complete:false});jobs[7].status='failed';expect(stageGate(batch,jobs)).toMatchObject({status:'failed',passed:7});});
test('历史输入、换行变体和共用参考图不能作为新案例重复计算',()=>{
 const {batch}=fixture();expect(()=>freezeStage(batch,[{prompt:'未见场景\n0'}])).toThrow('历史');
 batch.cases[0].imageIds=['a'.repeat(64)];expect(()=>freezeStage(batch,[{prompt:'不同描述',imageIds:['a'.repeat(64)]}])).toThrow('历史');
 batch.cases[1].imageIds=['a'.repeat(64)];expect(()=>freezeStage(batch,[])).toThrow('重复');
});
test('重复提交和后续重试不能抬高单次提交成功率',()=>{const {batch,jobs}=fixture();jobs.push({...jobs[8],id:'retry',status:'passed',attempt:2,retryRoot:'j8'});expect(stageGate(batch,jobs)).toMatchObject({status:'invalid',passed:8});const second={...jobs[0],id:'duplicate',retryRoot:'duplicate'};expect(stageGate(batch,[...jobs,second])!.cases[0].passed).toBe(false);});
test('手动修正、取消后续跑和只复评的通过不能补作原始提交',()=>{const {batch,jobs}=fixture();for(const field of ['reuseSceneFrom','reuseCheckpoint','recoverySourceJobId','reuseAssessmentFrom']){const edited=structuredClone(jobs);edited[0][field]='source';const r=stageGate(batch,edited)!;expect(r.passed).toBe(7);expect(r.complete).toBe(false);}});
test('版本、实际评分、硬门、关键需求或首稿被篡改均拒绝通过',()=>{const mutators=[(j:any)=>j.pipelineVersion={id:'new'},(j:any)=>j.profile={id:'other'},(j:any)=>j.runtime.hard.runtime=false,(j:any)=>j.spec.status='failed',(j:any)=>j.quality.criticalMissing=['R1'],(j:any)=>j.firstDraft={...j.firstDraft,score:84},(j:any)=>j.visualIterations.cycles.push({...j.visualIterations.cycles[1],index:2},{...j.visualIterations.cycles[1],index:3})];for(const mutate of mutators){const {batch,jobs}=fixture();mutate(jobs[0]);expect(stageGate(batch,jobs)!.cases[0].passed).toBe(false);expect(stageGate(batch,jobs)!.status).toBe('invalid');}});
test('固定清单或80分政策不能被放宽，二次提交政策不能用于阶段试验',()=>{const {batch,jobs}=fixture();batch.cases[0].prompt='替换简单样例';expect(stageGate(batch,jobs)!.status).toBe('invalid');batch.policy.maxAttempts=2;expect(()=>freezeStage(batch,[])).toThrow('一次');batch.policy.maxAttempts=1;batch.policy.score=70;expect(()=>freezeStage(batch,[])).toThrow('80');});
test('通过标签不能覆盖真实评审低置信度、分项低分或关键需求缺失',()=>{for(const mutate of [(j:any)=>j.review.confidence=.2,(j:any)=>j.review.dimensions.find((d:any)=>d.id==='spatial').score=1,(j:any)=>j.review.requirements[0].verdict='partial']){const {batch,jobs}=fixture();mutate(jobs[0]);expect(stageGate(batch,jobs)!.cases[0].passed).toBe(false);}});

test('硬门组合复用实际验收逻辑，不能遗漏构建、资产校验或提交帧率',()=>{for(const mutate of [(j:any)=>j.stages.build.status='failed',(j:any)=>j.stages.verify.status='failed',(j:any)=>j.runtime.submittedFps=5]){const {batch,jobs}=fixture();mutate(jobs[0]);expect(stageGate(batch,jobs)!.cases[0].passed).toBe(false);}});
