import {test,expect} from 'bun:test';
import {mkdtempSync,mkdirSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {save} from './store';
import {finishStage,finishInterrupted,generationPhase,elapsedTime} from './timing';
import {timingSnapshot} from './timing-snapshot';
test('结束与重启中断冻结时长，子步骤不会重复开始或丢失失败耗时',()=>{const j:any={createdAt:new Date(1000).toISOString(),status:'running',stages:{generate:{status:'running',startedAt:2000}},events:[]};generationPhase(j,'资产',2500);generationPhase(j,'资产',3000);expect(j.generationTimeline).toHaveLength(1);generationPhase(j,'组装',4000);expect(j.generationTimeline[0].durationMs).toBe(1500);finishInterrupted(j,5000);j.status='blocked';expect(elapsedTime(j,99999)).toBe(4000);expect(j.stages.generate.durationMs).toBe(3000);expect(j.generationTimeline[1].status).toBe('interrupted');expect(finishStage({startedAt:1000},'failed',1800,'error').durationMs).toBe(800);});
test('并发资产按墙钟历时与工作累计分别展示，历史复用耗时不混入，未知时间保持空',()=>{const root=mkdtempSync(join(tmpdir(),'timing-'));try{mkdirSync(join(root,'generation/assets'),{recursive:true});const steps=['a','b','old'].map(id=>({id,label:id,status:id==='old'?'reused':'passed'}));save(join(root,'generation/checkpoints.json'),{steps});for(const [id,start,end] of [['a',1000,5000],['b',2000,6000],['old',1,99999]] as const){mkdirSync(join(root,'generation/assets',id));save(join(root,'generation/assets',id,'checkpoint.json'),{status:'passed',readyAt:500,startedAt:start,endedAt:end,durationMs:end-start});}
 const j={id:'test',status:'cancelled',stage:'generate',createdAt:new Date(500).toISOString(),endedAt:6000,stages:{generate:{status:'cancelled',startedAt:1000}},generationLimits:{assetConcurrency:6}};const d=timingSnapshot(j,root,50000);expect(d.totalMs).toBe(5500);expect(d.assetWallMs).toBe(5000);expect(d.assetWorkMs).toBe(8000);expect(d.peakConcurrency).toBe(2);expect(d.assets[2].durationMs).toBe(0);expect(d.assets[0].queueMs).toBe(500);expect(d.stages[0].durationMs).toBeNull();expect(d.stages.find(x=>x.id==='generate')!.estimated).toBe(true);
 save(join(root,'generation/resumed-from.json'),{assets:[{id:'a'},{id:'b'},{id:'old'}]});save(join(root,'generation/checkpoints.json'),{steps:steps.map(s=>({...s,status:'pending'}))});const restored=timingSnapshot(j,root);expect(restored.assets.every((a:any)=>a.reused&&a.durationMs===0&&a.status==='reused')).toBe(true);expect(restored.assetWorkMs).toBe(0);expect(restored.peakConcurrency).toBe(0);
 }finally{rmSync(root,{recursive:true,force:true})}});

test('多轮导出运行和验收耗时累计保留，不只显示最后一轮',()=>{const root=mkdtempSync(join(tmpdir(),'timing-cycles-'));try{const j={id:'t',createdAt:new Date(0).toISOString(),status:'failed',endedAt:10000,stage:'gate',stages:{judge:{status:'passed',startedAt:5000,endedAt:8000,durationMs:3000}},stageAttempts:{judge:[{status:'passed',startedAt:1000,endedAt:3000,durationMs:2000}]}};const t=timingSnapshot(j,root).stages.find(s=>s.id==='judge')!;expect(t.durationMs).toBe(5000);expect(t.attempts).toHaveLength(2);}finally{rmSync(root,{recursive:true,force:true})}});
