import {bindObservedSpace} from './reference-observations';
import {validateAsset} from './layout';
import {join} from 'node:path';
import {mkdirSync,writeFileSync} from 'node:fs';
import {createServer} from 'node:net';
import {callValidated} from '../contracts';
import {ROOT,read,save,digest,saveJob,event} from '../store';
import {improvement} from '../improvement-governance';
import {prepareGeometryProject} from './prepare';
import {geometryProgramSchema,GEOMETRY_RULES} from './program-schema';
import {validateScene} from './scene-contract';
import {validateSpace,SPACE_PROMPT} from './layout-stages';
import {capturePlan} from './capture-plan.mjs';
const obj=(properties:any)=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false}),str={type:'string'},arr=(items:any)=>({type:'array',items});
export const blockoutSchema=()=>{const templates=structuredClone(geometryProgramSchema().properties.templates);const shape=templates.items.properties.parts.items.properties.shape;shape.anyOf=shape.anyOf.filter((variant:any)=>variant.properties.type.enum[0]!=='scatter');return obj({templates});};
export const spaceJudgeSchema=()=>obj({score:{type:'number'},confidence:{type:'number'},summary:str,relations:arr(obj({id:str,score:{type:'number'},verdict:{type:'string',enum:['met','partial','missing','uncertain']},reason:str,frames:arr(str)}))});
export function validateSpaceRelations(space:any){const r=space.spatialRelations;if(!Array.isArray(r)||!r.length||r.length>24||new Set(r.map(x=>x.id)).size!==r.length)throw Error('需要 1–24 项可观察的空间关系');for(const x of r)if(!x.id||!x.description?.trim()||typeof x.critical!=='boolean'||!x.instanceIds?.length||x.instanceIds.some(id=>!space.program.instances.some(i=>i.id===id)))throw Error('空间关系必须绑定实际实例');return space;}
export function spatialGate(review:any,space:any,frames:string[]){if(!Number.isFinite(review.score)||review.score<0||review.score>5||!Number.isFinite(review.confidence)||review.confidence<0||review.confidence>1)throw Error('空间评分无效');if(!Array.isArray(review.relations)||review.relations.length!==space.spatialRelations.length)throw Error('空间关系评估不完整');for(const r of space.spatialRelations){const xs=review.relations.filter(x=>x.id===r.id);if(xs.length!==1)throw Error('关系评估缺失或重复');const x=xs[0];if(!Number.isFinite(x.score)||x.score<0||x.score>5||!['met','partial','missing','uncertain'].includes(x.verdict)||!x.reason?.trim()||!x.frames?.length||x.frames.some(f=>!frames.includes(f)))throw Error('关系评分缺少有效截图证据');}const failed=space.spatialRelations.filter(r=>r.critical&&review.relations.some(x=>x.id===r.id&&(x.score<3||x.verdict!=='met')));return {passed:review.score>=4&&review.confidence>=.7&&!failed.length,failed:failed.map(r=>r.id),threshold:{space:4,critical:3,confidence:.7},review};}
const MATERIALS=[{id:'blockout',color:[.52,.55,.58,1],roughness:.85,metallic:0,textureId:null}];
export function blockoutScene(space:any,value:any,plan:any,referenceCount:number){if(!Array.isArray(value.templates)||value.templates.length!==space.program.templates.length||new Set(value.templates.map(t=>t.id)).size!==value.templates.length||space.program.templates.some(t=>!value.templates.some(v=>v.id===t.id)))throw Error('灰模须保留全部冻结模板');const errors:string[]=[];for(const template of value.templates){if(template.parts.length>32)errors.push(`灰模模板 ${template.id} 超过 32 个部件`);for(const part of template.parts){if(part.material!=='blockout')errors.push(`灰模模板 ${template.id} 的部件 ${part.id} 只能使用 blockout 材质`);if(part.shape.type==='scatter')errors.push(`灰模模板 ${template.id} 的部件 ${part.id} 禁止 scatter；请用少量独立基础部件表达主要轮廓`);}}if(errors.length)throw Error('灰模资产检查失败：'+errors.join('；'));for(const brief of space.program.templates){try{validateAsset({version:'asset-geometry-v1',template:value.templates.find(t=>t.id===brief.id)},{...brief,maxParts:32,materialIds:['blockout']},{...space,program:{...space.program,materials:MATERIALS}},{});}catch(error){errors.push(String(error));}}if(errors.length)throw Error('灰模资产检查失败：'+errors.join('；'));return validateScene({...space,version:'scene-v1',textures:[],textureReuse:[],program:{...space.program,materials:MATERIALS,templates:value.templates},lighting:{direction:[.4,-.6,-.7],color:[1,1,1],intensity:1.8,ambientColor:[1,1,1],ambientIntensity:.65,points:[]}},plan,referenceCount);}
async function renderBlockout(scene:any,folder:string,ctx:any,command:any){const project=join(folder,'project'),out=join(folder,'runtime');mkdirSync(out,{recursive:true});prepareGeometryProject(project,scene.program,{}, {id:'graybox-'+ctx.job.id,summary:'参考图空间与相机验收灰模',scene,provenance:{baselineId:ctx.job.baselineId,kind:'spatial-blockout',pipelineVersion:ctx.job.pipelineVersion}});const proto=join(ROOT,'../prototype/bin/pipeline.ts');for(const args of [['bun',proto,'generate'],['bun',join(ROOT,'src/geometry/export.ts'),project],['bun',join(ROOT,'src/sync-bindings.ts'),project],['bun',proto,'build'],['bun',proto,'verify']])await command(args,240000,project);
 const port=await new Promise<number>((res,rej)=>{const s=createServer();s.once('error',rej);s.listen(0,'::1',()=>{const p=(s.address() as any).port;s.close(()=>res(p));});});const game=join(project,'game'),p=Bun.spawn(['node',join(ROOT,'../engine/packages/engine/dist/bin/forgeax.mjs'),'project','preview','--root',game,'--port',String(port),'--json'],{cwd:game,stdout:'pipe',stderr:'pipe'});let logs='';const pump=async(s:any)=>{for await(const b of s){logs+=new TextDecoder().decode(b);writeFileSync(join(folder,'preview.log'),logs)}};void pump(p.stdout);void pump(p.stderr);const url='http://localhost:'+port+'/';try{let ready=false;for(let n=0;n<80;n++){ctx.signal.throwIfAborted();if(p.exitCode!==null)throw Error('灰模 Engine 预览启动失败：'+logs.slice(-500));try{const r=await fetch(url,{signal:AbortSignal.timeout(500)});await r.body?.cancel();if(r.ok){ready=true;break;}}catch{}await Bun.sleep(250);}if(!ready)throw Error('灰模 Engine 预览启动超时');await command(['node',join(ROOT,'src/geometry/capture.mjs'),game,url,out],capturePlan(scene.cameras.length).stageTimeoutMs,project);const runtime=read(join(out,'runtime.json'));if(runtime.distManifestDigest!==read(join(project,'evidence/run-report.json')).distManifestDigest)throw Error('灰模画面与构建产物不一致');if(!runtime.hard.runtime||!runtime.hard.noErrors||!runtime.hard.multipleViews)throw Error('灰模运行或多视角证据未通过');return runtime;}finally{p.kill();await p.exited;}}
export async function acceptSpatialLayout(initial:any,ctx:any,command:any,stage:any){let space=validateSpaceRelations(initial),feedback:any=null,round=0;const {job,plan,images,signal}=ctx;job.blockout={status:'running',rounds:[]};saveJob(job);
 while(true){const folder=join(ctx.dir,'blockout',String(round));mkdirSync(folder,{recursive:true});const startedAt=Date.now();save(join(folder,'space.json'),space);
  const value=await stage('graybox',async()=>{const geometry=ctx.existingScene?{value:{templates:ctx.existingScene.program.templates.map(t=>({...t,parts:t.parts.map(p=>({...p,material:'blockout'}))}))}}:await callValidated({role:'scene-blockout',modelSettings:job.modelSettings,signal,maxTokens:16000,images,system:'根据冻结空间规划生成用于检验构图的三维灰模。只输出 templates，不改变实例、相机或布局。每个模板使用 1–32 个简单部件，不做纹理与小装饰；保留物体轮廓、门窗真正的净空、通道与后方纵深。所有材质只用 blockout。模板局部原点与 bounds 必须服从规划。各参考图共享同一个三维空间。\n'+GEOMETRY_RULES+'\n灰模阶段只允许 box、lathe、extrusion、tube、grid 五类基础形状；禁止 scatter，重复的小部件只保留能表达主要轮廓的少量独立部件。',text:JSON.stringify({space,previousFeedback:feedback})},folder,v=>{blockoutScene(space,v,plan,images.length);return v});const scene=ctx.existingScene?validateScene({...ctx.existingScene,textures:[],textureReuse:[],program:{...ctx.existingScene.program,materials:MATERIALS,templates:geometry.value.templates},lighting:{direction:[.4,-.6,-.7],color:[1,1,1],intensity:1.8,ambientColor:[1,1,1],ambientIntensity:.65,points:[]}},plan,images.length):blockoutScene(space,geometry.value,plan,images.length);save(join(folder,'scene.json'),scene);const runtime=await renderBlockout(scene,folder,ctx,command);const frameNames=runtime.referenceFrames.filter(f=>f.referenceIndex).map(f=>f.file),frames=frameNames.map(file=>({path:join(folder,'runtime',file),mime:'image/png'}));const result=await callValidated({role:'scene-space-judge',modelSettings:job.modelSettings,signal,maxTokens:6000,images:[...images,...frames],system:'你是独立空间验收员。前面的图片是已确认参考图，后面是同参考机位的 ForgeaX 灰模实拍。仅评空间比例、相机透视、主体布局、遮挡、开口通道和可见纵深，不因无材质而扣分，也不能忽略缺失的大轮廓。逐项核对冻结空间关系，使用真实帧名。评分 0–5，4 表示主体关系与构图基本一致，仅局部可见偏差，3 表示多个明显比例或机位错误。对关键关系，uncertain 或 partial 都不能称为满足。综合 score 须覆盖所有参考图，confidence 表示证据充分度。不要相信规划文字所声称的成功。',text:JSON.stringify({referenceCount:images.length,frameNames,observation:ctx.observation,bindings:space.observedBindings,relations:space.spatialRelations,cameras:space.cameras})},folder,v=>{spatialGate(v,space,frameNames);return v});const gate=spatialGate(result.value,space,frameNames);return {...gate,frames:frameNames,runtimeDigest:runtime.distManifestDigest};});
  const row={round,startedAt,endedAt:Date.now(),...value,path:'generation/blockout/'+round};save(join(folder,'gate.json'),row);job.blockout.rounds.push(row);job.blockout.status=value.passed?'passed':'failed';if(!value.passed&&job.stages?.graybox)job.stages.graybox.status='failed';job.blockout.spaceSha256=digest(JSON.stringify(space));saveJob(job);improvement.result(job.improvementId,{kind:'space',comparison:'spatial-blockout-v1',jobId:job.id,round,score:value.review.score*20,status:value.passed?'passed':'failed'});
  if(value.passed){job.blockout.space=space;saveJob(job);save(join(ctx.dir,'space.json'),space);return space;}
  feedback=value.review;if(ctx.existingScene)throw Error('SPATIAL_GATE_FAILED：恢复候选空间未通过，保留证据；请先调整空间规划，不继续细化资产');if(!improvement.remaining(job.improvementId)){job.blockout.status='stopped';saveJob(job);throw Error('SPATIAL_GATE_FAILED：空间灰模未通过，停止详细资产生成；已保留截图、关系评分和诊断');}
  improvement.reserveRepair(job.improvementId,'graybox',feedback.summary);event(job,'spatial-repair','灰模未通过，先依据实际画面修正空间规划；资产尚未开始');round++;const repairDir=join(ctx.dir,'space-repair-'+round);mkdirSync(repairDir,{recursive:true});const next=await stage('space',()=>callValidated({role:'scene-space',modelSettings:job.modelSettings,signal,maxTokens:11000,images:[...images,...value.frames.map(f=>({path:join(folder,'runtime',f),mime:'image/png'}))],system:SPACE_PROMPT+'\n原始参考图在前，灰模反馈图在后。依据明确关系差距修改位置、比例或相机；保留正确部分，不把灰模错误当参考，不加入无关物件。',schemaContext:{requirementIds:plan.requirements.map(r=>r.id)},text:JSON.stringify({input:job.prompt,referenceImages:images.length,plan,generationBrief:job.generationBrief,previousSpace:space,observation:ctx.observation,feedback})},repairDir,v=>{const checked=validateSpaceRelations(validateSpace(v,plan,images.length,job.complexity));return ctx.observation?bindObservedSpace(checked,ctx.observation):checked;}));space=next.value;
 }
}
