import {test,expect} from 'bun:test';
import {boundedIterations} from './iteration-policy';
function setup(rows:{status:string;score:number}[],maxRepairs=2){const snapshots:any[]=[],sources:any[]=[],ctl=new AbortController();return {snapshots,sources,ctl,options:{maxRepairs,signal:ctl.signal,canRefine:()=>true,evaluate:async(i:number)=>rows[i],snapshot:async(c:any)=>{snapshots.push(structuredClone(c));},refine:async(i:number,n:number)=>{sources.push([i,n]);}}};}
test('用户只提交一次：首稿不通过、两轮修正后通过，成绩均保留',async()=>{const s=setup([{status:'failed',score:56},{status:'failed',score:73},{status:'passed',score:83}]);const r=await boundedIterations(s.options);expect(r.bestIndex).toBe(2);expect(r.firstDraft.score).toBe(56);expect(r.firstDraft.status).toBe('failed');expect(s.sources).toEqual([[0,1],[1,2]]);expect(s.snapshots.map(c=>c.score)).toEqual([56,73,83]);expect(r.stopReason).toBe('passed');});
test('变差就停止，不能用最新结果覆盖最佳结果',async()=>{const s=setup([{status:'failed',score:65},{status:'failed',score:54}]);const r=await boundedIterations(s.options);expect(r.bestIndex).toBe(0);expect(r.stopReason).toBe('no-improvement');expect(s.sources).toHaveLength(1);});
test('首稿已通过时零修正；未通过也不超过两轮',async()=>{let s=setup([{status:'passed',score:83}]);expect((await boundedIterations(s.options)).cycles).toHaveLength(1);expect(s.sources).toHaveLength(0);s=setup([{status:'failed',score:60},{status:'failed',score:70},{status:'failed',score:79}]);expect((await boundedIterations(s.options)).stopReason).toBe('limit');expect(s.sources).toHaveLength(2);await expect(boundedIterations({...s.options,maxRepairs:3})).rejects.toThrow('两轮');});
test('预算不足保留首稿；取消不会启动下一轮；模型异常不自动重试',async()=>{const s=setup([{status:'failed',score:60}]);expect((await boundedIterations({...s.options,canRefine:()=>false})).stopReason).toBe('budget');expect(s.sources).toHaveLength(0);s.ctl.abort();await expect(boundedIterations(s.options)).rejects.toThrow();const b=setup([{status:'failed',score:60}]);await expect(boundedIterations({...b.options,refine:async()=>{throw Error('PROVIDER_TIMEOUT')}})).rejects.toThrow('PROVIDER_TIMEOUT');expect(b.snapshots).toHaveLength(1);});

test('零点几分的波动不作为改进，保留原候选且停止后续调用',async()=>{const s=setup([{status:'failed',score:55.7},{status:'failed',score:56.1}]);const r=await boundedIterations(s.options);expect(r.bestIndex).toBe(0);expect(r.stopReason).toBe('no-improvement');expect(r.cycles[1].score).toBe(56.1);expect(s.sources).toHaveLength(1);});
