import {callValidated} from '../contracts';
import {join} from 'node:path';
import {mkdirSync} from 'node:fs';
import {save} from '../store';
const str={type:'string'},num={type:'number'},obj=(properties:any)=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false}),arr=(items:any)=>({type:'array',items});
export const observationSchema=(count?:number)=>{const referenceIndex={type:'integer',minimum:1,...(count?{maximum:count}:{})};return obj({landmarks:arr(obj({id:str,label:str,critical:{type:'boolean'},views:arr(obj({referenceIndex,box:{type:'array',items:num,minItems:4,maxItems:4},evidence:str}))})),relations:arr(obj({id:str,description:str,critical:{type:'boolean'},landmarkIds:arr(str)})),cameras:arr(obj({referenceIndex,evidence:str,uncertainty:str})),assumptions:arr(str)});};
export function validateObservations(v:any,count:number){if(!v?.landmarks?.length||v.landmarks.length>50||new Set(v.landmarks.map(l=>l.id)).size!==v.landmarks.length)throw Error('观察记录需要 1–50 个不重复地标');for(const l of v.landmarks){if(!l.label?.trim()||typeof l.critical!=='boolean'||!l.views?.length)throw Error('地标必须有图片证据');for(const r of l.views){if(!Number.isInteger(r.referenceIndex)||r.referenceIndex<1||r.referenceIndex>count)throw Error(`地标图片序号 referenceIndex 必须为 1..${count}，第一张是 1，不能从 0 开始`);if(!r.evidence?.trim()||r.box?.length!==4||r.box.some(n=>!Number.isFinite(n)||n<0||n>1)||r.box[0]>=r.box[2]||r.box[1]>=r.box[3])throw Error('地标包围框或图片证据无效');}}if(!v.relations?.length||v.relations.length>24||new Set(v.relations.map(r=>r.id)).size!==v.relations.length)throw Error('关系观察须为 1–24 项');for(const r of v.relations)if(!r.description?.trim()||!r.landmarkIds?.length||r.landmarkIds.some(id=>!v.landmarks.some(l=>l.id===id)))throw Error('关系须引用图中地标');if(v.cameras?.length!==count||new Set(v.cameras.map(c=>c.referenceIndex)).size!==count||v.cameras.some(c=>!Number.isInteger(c.referenceIndex)||c.referenceIndex<1||c.referenceIndex>count||!c.evidence?.trim()))throw Error(`每张图必须有独立机位依据，referenceIndex 必须覆盖 1..${count}，不能从 0 开始`);return v;}
export async function observeReferences(ctx:any){mkdirSync(ctx.dir,{recursive:true});const r=await callValidated({role:'scene-observation',modelSettings:ctx.job.modelSettings,signal:ctx.signal,maxTokens:9000,images:ctx.images,schemaContext:{referenceCount:ctx.images.length},system:'先观察参考图，不设计或生成场景。逐张图记录可见地标与遮挡，再确认跨视角对应。同一物体的不同视角共用地标 ID；只看到一部分就只陈述可见部分，不能凭题材添加未见家具、房间或通道。图片序号 referenceIndex 从 1 开始：第一张为 1、第二张为 2，绝不能用 0；landmarks 的各 views 与 cameras 都遵守相同编号。landmarks 包含 id、中文 label、critical 和各 views，view 包含 referenceIndex、box=[左,上,右,下]（完整输入图归一化坐标，排除黑边与水印）、具体 evidence。覆盖建筑大结构、主要物体及地面；细小同类零散物可按有证据的组记录。relations 只包含图片能支持的前后左右、尺度比例、遮挡、开口与纵深；绑定 landmarkIds，关键构图关系设 critical。cameras 每张一项，记录观察方向、透视线与高度的可见依据和 uncertainty，暂不编造绝对坐标。看不见的背面与尺度猜测只记 assumptions。全部使用中文，只输出 JSON。',text:JSON.stringify({prompt:ctx.job.prompt,referenceCount:ctx.images.length,referenceIndices:ctx.images.map((_:unknown,index:number)=>index+1),requirements:ctx.plan.requirements})},ctx.dir,v=>validateObservations(v,ctx.images.length));save(join(ctx.dir,'reference-observations.json'),r.value);return r.value;}
export function bindObservedSpace(space:any,observation:any){const bindings=space.observedBindings;if(!Array.isArray(bindings)||bindings.length!==observation.landmarks.length||new Set(bindings.map(b=>b.landmarkId)).size!==bindings.length)throw Error('每个已观察地标都必须绑定空间实例');for(const l of observation.landmarks){const b=bindings.find(b=>b.landmarkId===l.id);if(!b?.instanceIds?.length||b.instanceIds.some(id=>!space.program.instances.some(i=>i.id===id)))throw Error('地标缺少真实实例绑定：'+l.id);}for(const i of space.program.instances)if(!bindings.some(b=>b.instanceIds.includes(i.id)))throw Error('实例没有原图地标依据，禁止凭空添加：'+i.id);if(space.spatialRelations?.length!==observation.relations.length)throw Error('不能删除或新增已冻结的空间关系');for(const r of observation.relations){const x=space.spatialRelations.find(x=>x.id===r.id);if(!x||x.critical!==r.critical||x.description!==r.description)throw Error('不得更改观察关系或降低关键性：'+r.id);const expected=[...new Set(r.landmarkIds.flatMap(id=>bindings.find(b=>b.landmarkId===id).instanceIds))];if(JSON.stringify([...x.instanceIds].sort())!==JSON.stringify(expected.sort()))throw Error('关系实例必须对应原地标：'+r.id);}return space;}
