import {test,expect} from 'bun:test';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {refinementBaseline,comparableAssessment} from './refinement-baseline';
import {DEFAULT_POLICY,DIMENSIONS,HARD_CHECKS} from '../quality';
import {VISUAL_RULE_IDS} from '../spec';
import {digest,save,runDir} from '../store';
function fixture(){
 const root=mkdtempSync(join(tmpdir(),'repair-baseline-')),sourceDir=join(root,'source'),folder=join(root,'refinement'),id=crypto.randomUUID(),targetDir=runDir(id);
 for(const p of ['project/evidence','project/game/dist','runtime'])mkdirSync(join(sourceDir,p),{recursive:true});mkdirSync(targetDir,{recursive:true});
 const frame='source-frame',dist='source-build',frames=['reference-1.png'];writeFileSync(join(sourceDir,'runtime',frames[0]),frame);writeFileSync(join(sourceDir,'project/game/dist/forgeax-dist.json'),dist);
 const profile={engineSha:'a'.repeat(40),generatorSha:'b'.repeat(40),provider:'codex-cli',judgeModel:'same-model',reasoningEffort:'high',assessmentProtocolSha256:'old',specSha256:'spec',policy:DEFAULT_POLICY,executionRoute:{configurationSha256:'same-route'}};
 save(join(sourceDir,'project/evidence/run-report.json'),{...profile,distManifestDigest:digest(dist),buildInputDigest:'d'.repeat(64),catalog:{sha256:'e'.repeat(64)},stages:Object.fromEntries(['candidate','generate-export','generation-budget','publish-assets','engine-binding','project-check','engine-build','catalog','asset-verify','asset-ready','engine-status'].map(k=>[k,{status:'passed'}]))});
 const plan={requirements:[{id:'R1',critical:true,weight:1}],capabilities:['mapping']},runtime={hard:Object.fromEntries(HARD_CHECKS.map(k=>[k,true])),submittedFps:30,images:frames,hashes:[digest(frame)],distManifestDigest:digest(dist)};
 const review={requirements:[{id:'R1',verdict:'met',reason:'Visible',frames}],dimensions:DIMENSIONS.map(d=>({id:d.id,score:4,reason:'Visible',frames})),specRules:VISUAL_RULE_IDS.map(id=>({id,status:'passed',reason:'Visible',frames})),entityCounts:[{kind:'structure',visibleMin:1,visibleMax:1}],confidence:.9};
 const source:any={id:'source',profile,policy:DEFAULT_POLICY,plan,runtime,images:[],prompt:'原图',structure:{passed:true,semanticCounts:{structure:1}},modelSettings:{model:'same-model',reasoningEffort:'high'},stages:{build:{status:'passed'},verify:{status:'passed'}},quality:{score:61},review:{old:true},pipelineVersion:{id:'old-version'}};
 save(join(sourceDir,'generated-scene.json'),{entities:[{instanceId:'one',category:'structure'}],program:{instances:[{id:'one',label:'single structure'}]}});save(join(sourceDir,'job.json'),source);
 const job:any={...source,id,events:[],profile:{...profile,assessmentProtocolSha256:'new'}};save(join(targetDir,'job.json'),job);
 return {root,sourceDir,folder,targetDir,source,job,review,cleanup(){rmSync(root,{recursive:true,force:true});rmSync(targetDir,{recursive:true,force:true});}};
}
test('same contract uses saved baseline without another model call',async()=>{const f=fixture();try{f.job.profile=f.source.profile;const r=await refinementBaseline(f.job,f.source,f.sourceDir,f.folder,new AbortController().signal,3,async()=>{throw Error('must not call')});expect(r).toEqual({review:f.source.review,quality:f.source.quality,reassessed:false});expect(existsSync(join(f.folder,'baseline'))).toBe(false);}finally{f.cleanup();}});
test('contract migration evaluates immutable old frames and reserves remaining repair and scoring calls',async()=>{const f=fixture();try{const before=readFileSync(join(f.sourceDir,'job.json'),'utf8');let calls=0;const response=await refinementBaseline(f.job,f.source,f.sourceDir,f.folder,new AbortController().signal,3,async(input,dir,validate)=>{calls++;expect(input.role).toBe('judge');expect(input.reservedCalls).toBe(3);expect(input.images[0].path).toBe(join(f.sourceDir,'runtime/reference-1.png'));expect(JSON.parse(input.text).countUnits[0].units[0].instanceId).toBe('one');return {value:validate(f.review),receipt:{stopReason:'completed'}} as any;});expect(calls).toBe(1);expect(response.reassessed).toBe(true);expect(response.quality.score).toBe(85.6);expect(f.job.refinementBaseline.originalScore).toBe(61);expect(f.job.refinementBaseline.profile).toEqual(f.job.profile);expect(comparableAssessment({profile:f.job.refinementBaseline.profile,plan:f.source.plan},f.job)).toBe(true);expect(JSON.parse(readFileSync(join(f.folder,'baseline/review.json'),'utf8'))).toEqual(f.review);expect(readFileSync(join(f.sourceDir,'job.json'),'utf8')).toBe(before);}finally{f.cleanup();}});
test('tampered baseline evidence fails before any model call',async()=>{const f=fixture();try{writeFileSync(join(f.sourceDir,'runtime/reference-1.png'),'tampered');let calls=0;await expect(refinementBaseline(f.job,f.source,f.sourceDir,f.folder,new AbortController().signal,3,async()=>{calls++;return {} as any;})).rejects.toThrow('画面摘要');expect(calls).toBe(0);expect(f.job.refinementBaseline).toBeUndefined();}finally{f.cleanup();}});
test('blocked baseline preserves source and does not claim it is comparable',async()=>{const f=fixture();try{await expect(refinementBaseline(f.job,f.source,f.sourceDir,f.folder,new AbortController().signal,3,async()=>{throw Error('MODEL_BUDGET_EXHAUSTED');})).rejects.toThrow('MODEL_BUDGET_EXHAUSTED');expect(f.job.refinementBaseline).toBeUndefined();expect(existsSync(join(f.folder,'baseline/quality.json'))).toBe(false);expect(f.source.quality.score).toBe(61);}finally{f.cleanup();}});
